### ISSUE TITLE
Standardization of ProjectType class across QPR_EEs and implementation of choices_project_type template  for UI SPM radio components

### ISSUE THREAD

**Issue by yogat3ch** [COHHIO/Rminor#36]
I'm noticing the following `mutate` call at various intervals throughout *server.R*:
```
 %>%
        mutate(
          ProjectType = case_when(
            ProjectType == 1 ~ "Emergency Shelters",
            ProjectType == 2 ~ "Transitional Housing",
            ProjectType %in% c(3, 9) ~ "Permanent Supportive Housing",
            ProjectType == 4 ~ "Street Outreach",
            ProjectType == 8 ~ "Safe Haven",
            ProjectType == 12 ~ "Homelessness Prevention",
            ProjectType == 13 ~ "Rapid Rehousing"
          )
        )
```

I took a look at the class types for `ProjectType` in the various datasets used in the SPM subitems:
```
qpr_benefits       qpr_income      qpr_leavers qpr_rrh_enterers 
     "character"      "character"        "numeric"        "numeric" 
    qpr_spending            goals       validation 
       "numeric"        "numeric"        "numeric"
```

The shiny UI components allow for `choices` to be provided as a named list wherein the user will be supplied with the names of the items, and the server will be supplied with the vector values.  
Combining the choices from the `project_type` function and the number correspondences from the code chunk above yields the following map (in alphabetic order):

```
choices_project_type <- list(
  `Coordinated Entry` = 14,
  `Emergency Shelters` = 1, 
  `Homelessness Prevention` = 12, 
  `Permanent Supportive Housing` = c(3, 9),
  `Rapid Rehousing` = 13,
  `Safe Haven` = 8, 
  `Services Only` = 6,
  `Street Outreach` = 4, 
  `Transitional Housing` = 2
)
```

Can we discuss the merits/drawbacks of the following?:
Option 1:
1. Standardize the representation of this ProjectType variable to numeric across the objects in which it appears (in COHHIO_HMIS)
2. Use `choices_project_type` with a subset `[` as inputs for `choices` argument to UI components
3. Eliminate the server-side `mutate` calls mentioned above
4. Allow filter by the `input$radio...` object directly
5. Remove the potential for class type conflicts when joining

Option 2: 
The alternative would be to standardize to `character` representations in the data (changes on the COHHIO_HMIS side) and then use just the names as a character vector that can be subsetted as the value for `choices` in UI components. 
This would also accomplish 3:5, and be more human legible to the developer.

**Comment by trevinflick** [comment]
No longer used
