### ISSUE TITLE
Add functionality to Utilization plot (select multiple providers)

### ISSUE THREAD

**Issue by kiadso** [COHHIO/Rminor#38]
A user asked for the ability to see multiple providers' Utilization on one screen. They've been taking the total infoboxes from Rme and pasting them into a pdf. Will update as I find out more from the user (Linda R) as to how that is being used.

**Comment by yogat3ch** [comment]
This sounds like it's going to be a great place to iteratively render graphs based on the vector supplied by input$providers. 
Will also likely need a checkbox to switch on "Compare across providers" mode, or something of that nature.

If we wanted to get really fancy we could make it such that the selected location on a single plot brings up the tooltip for the selected location across all plots such that the TT can be easily compared in a single glance. This is a built-in plotly feature now that just needs to be setup I believe.
