### ISSUE TITLE
Text field for Veterans Populated as Youth

### ISSUE THREAD

**Issue by entomacy** [COHHIO/Rminor#54]
![Screen Shot 2023-09-11 at 3 25 40 PM](https://github.com/COHHIO/Rminor/assets/16522277/a03907e1-e9ab-4ffe-b386-546db67528d5)

Counties Served by Access Point for Youth and Counties Served by Access Point for Veterans are getting mixed up in the CE Access points table of Rm.

**Comment by trevinflick** [comment]
This issue was fixed in Looker, table Provider Extras
